# Generated by Django 3.2 on 2022-11-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0004_auto_20221103_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='备注'),
        ),
    ]
