# Generated by Django 3.2 on 2022-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0005_userinfo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='部门名称'),
        ),
    ]
