# Generated by Django 3.2 on 2022-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0007_auto_20221109_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='department',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
    ]
