# Generated by Django 3.2 on 2022-12-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0009_department_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_check',
            field=models.CharField(default='0', max_length=10, verbose_name='是否资产盘点员'),
        ),
    ]
