# Generated by Django 3.2 on 2022-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0010_userinfo_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_check',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.CharField(default='0', max_length=5, verbose_name='管理等级'),
        ),
    ]
