# Generated by Django 3.2 on 2022-12-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataControl', '0010_resource_duty'),
        ('userControl', '0010_userinfo_is_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='表单名')),
                ('is_check', models.CharField(max_length=10, verbose_name='盘点状态')),
                ('check_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userControl.userinfo', verbose_name='资产盘点员')),
            ],
        ),
        migrations.CreateModel(
            name='checkRes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10, verbose_name='是否已盘')),
                ('t_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkControl.check', verbose_name='资产盘点表')),
                ('t_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataControl.resource', verbose_name='资产表')),
            ],
        ),
    ]
