# Generated by Django 3.2 on 2022-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0010_resource_duty'),
        ('checkControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkRes',
            new_name='check_resource',
        ),
    ]
