# Generated by Django 3.2 on 2022-12-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0010_userinfo_is_check'),
        ('checkControl', '0002_rename_checkres_check_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='is_check',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='check_resource',
            old_name='status',
            new_name='is_checked',
        ),
        migrations.RemoveField(
            model_name='check',
            name='check_admin',
        ),
        migrations.CreateModel(
            name='check_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkControl.check', verbose_name='盘点表')),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userControl.userinfo', verbose_name='盘点员')),
            ],
        ),
    ]
