# Generated by Django 3.2 on 2022-12-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0003_auto_20221209_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='comment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(default='0', max_length=10, verbose_name='盘点状态'),
        ),
    ]
