# Generated by Django 3.2 on 2022-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0004_auto_20221209_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='盘点公司'),
        ),
        migrations.AddField(
            model_name='check',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
