# Generated by Django 3.2 on 2022-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0005_auto_20221209_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_resource',
            name='is_checked',
            field=models.CharField(default='0', max_length=10, verbose_name='是否已盘'),
        ),
    ]
