# Generated by Django 3.2 on 2022-12-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0006_alter_check_resource_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='盘点员姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='盘点员手机号')),
                ('t_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkControl.check', verbose_name='盘点表')),
            ],
        ),
        migrations.DeleteModel(
            name='check_user',
        ),
    ]
