# Generated by Django 3.2 on 2023-01-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0008_alter_check_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check_resource',
        ),
    ]
