# Generated by Django 3.2 on 2023-01-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0012_resourceprovider'),
        ('checkControl', '0009_delete_check_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_checked', models.CharField(default='0', max_length=10, verbose_name='是否已盘')),
                ('t_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkControl.check', verbose_name='资产盘点表')),
                ('t_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataControl.resource', verbose_name='资产表')),
            ],
        ),
    ]
