# Generated by Django 3.2 on 2022-11-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinfo',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级'),
        ),
    ]
