# Generated by Django 3.2 on 2022-11-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0002_alter_resourceinfo_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceUnits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='计量单位')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='resourcelocation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='资产存放区域'),
        ),
    ]
