# Generated by Django 3.2 on 2022-11-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0009_department_company'),
        ('dataControl', '0004_auto_20221110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='borrow_department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='借用部门'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userControl.department', verbose_name='所属部门'),
        ),
    ]
