# Generated by Django 3.2 on 2022-11-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0005_auto_20221111_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataControl.resourcetype', verbose_name='类型展示'),
        ),
    ]
