# Generated by Django 3.2 on 2022-12-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0007_auto_20221130_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='department',
        ),
    ]
