# Generated by Django 3.2 on 2022-12-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0009_department_company'),
        ('dataControl', '0008_remove_resource_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userControl.department', verbose_name='所属部门'),
        ),
    ]
