# Generated by Django 3.2 on 2022-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0009_resource_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='duty',
            field=models.CharField(default='暂无', max_length=20, verbose_name='责任人'),
        ),
    ]
