# Generated by Django 3.2 on 2022-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0011_resourcename'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='供应商')),
            ],
        ),
    ]
