# Generated by Django 3.2 on 2023-01-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkControl', '0011_remove_check_resource_t_resource'),
        ('dataControl', '0012_resourceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resource',
        ),
        migrations.DeleteModel(
            name='resourceInfo',
        ),
    ]
