# Generated by Django 3.2 on 2023-01-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userControl', '0013_company_is_header'),
        ('dataControl', '0013_auto_20230104_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='入库时间')),
                ('buy_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='购买日期')),
                ('resource_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='资产原值')),
                ('depreciation_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='折旧周期')),
                ('residuals_rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='残值率')),
                ('resource_residuals', models.CharField(blank=True, max_length=20, null=True, verbose_name='资产残值')),
                ('month_depreciation', models.CharField(blank=True, max_length=20, null=True, verbose_name='月折旧额')),
                ('total_depreciation', models.CharField(blank=True, max_length=20, null=True, verbose_name='累计折旧')),
                ('net_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='资产净值')),
                ('specifications', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格型号')),
                ('units', models.CharField(blank=True, max_length=20, null=True, verbose_name='计量单位')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='供应商')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='SN号')),
                ('comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产名')),
                ('code', models.CharField(default='0', max_length=20, verbose_name='资产编码')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放地点')),
                ('location_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放区域')),
                ('duty', models.CharField(default='暂无', max_length=20, verbose_name='责任人')),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='借用人')),
                ('borrow_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='借用部门')),
                ('resource_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产来源')),
                ('resource_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产状态')),
                ('borrow_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='借用时间')),
                ('return_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='预归还时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userControl.company', verbose_name='所属公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userControl.department', verbose_name='所属部门')),
                ('detail_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataControl.resourceinfo', verbose_name='资产详情')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataControl.resourcetype', verbose_name='类型展示')),
            ],
        ),
    ]
