# Generated by Django 3.2 on 2023-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0014_resource_resourceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='duty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='责任人'),
        ),
    ]
